name: GitHub TruffleHog Action Test
run-name: ${{ github.actor }} running TruffleHog
on:
    push:
      branches:
        - main
        - test
    pull_request:
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
        - name: Secret Scanning
          uses: trufflesecurity/trufflehog@main
          with:
            extra_args: --debug --only-verified
        - name: Scan entire branch
          uses: trufflesecurity/trufflehog@main
          with:
            path: /
            base: ""
            head: ${{ github.ref_name }}
            extra_args: --debug --only-verified
