name: GitHub TruffleHog Action Test
run-name: ${{ github.actor }} running TruffleHog
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - name: TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        # Repository path
        path: /
        # Start scanning from here (usually main branch).
        base: main
        # Scan commits until here (usually dev branch).
        head: # optional
        # Extra args to be passed to the trufflehog cli.
        extra_args: --debug --only-verified
