name: GitHub TruffleHog Action Test
run-name: ${{ github.actor }} running TruffleHog

on:
    push:
      branches:
        - main
    pull_request:

permissions:
    contents: read
    id-token: write
    issues: write
    pull-requests: write

jobs:
    trufflehog:
        runs-on: ubuntu-latest
        defaults:
          run:
            shell: bash
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: scan secrets
          id: scansecrets
          uses: trufflesecurity/trufflehog@main
          continue-on-error: true
          with:
            extra_args: --debug --only-verified

        - name: scan branch
          id: scanbranch
          uses: trufflesecurity/trufflehog@main
          continue-on-error: true
          with:
            path: /
            base: ""
            head: ${{ github.ref_name }}
            extra_args: --debug --only-verified

        - name: Scan Results Status
          if: steps.scansecrets.outcome == 'failure' ||  steps.scanbranch.outcome == 'failure'
          run: exit 1
